projectName: platform
image: jembi/platform:latest
logPath: /tmp/logs

packages:
  - fhir-datastore-hapi-fhir
  - hapi-fhir-server

profiles:
  - name: cdr-dw
    packages:
      - interoperability-layer-openhim
      - reverse-proxy-nginx
      - fhir-datastore-hapi-fhir
      - message-bus-kafka
      - job-scheduler-ofelia
      - kafka-mapper-consumer
      - kafka-unbundler-consumer
      - analytics-datastore-clickhouse
      - dashboard-visualiser-superset
      - monitoring
      - mpi-mediator
      - client-registry-jempi
      - identity-access-manager-keycloak
      - openhim-mapping-mediator
    envFiles:
      - cdr-dw.env

  - name: cdr
    packages:
      - interoperability-layer-openhim
      - reverse-proxy-nginx
      - fhir-datastore-hapi-fhir
      - message-bus-kafka
      - job-scheduler-ofelia
      - kafka-unbundler-consumer
      - monitoring
      - mpi-mediator
      - client-registry-jempi
      - identity-access-manager-keycloak
      - openhim-mapping-mediator
    envFiles:
      - cdr.env

  - name: mpi
    packages:
      - interoperability-layer-openhim
      - reverse-proxy-nginx
      - message-bus-kafka
      - job-scheduler-ofelia
      - monitoring
      - client-registry-jempi
      - identity-access-manager-keycloak
      - openhim-mapping-mediator
    envFiles:
      - mpi.env