version: '3.9'

services:
  identity-access-manager-keycloak:
    image: keycloak/keycloak:23.0
    command:
      [
        "start",
        "--proxy=edge",
        "--hostname-url=${KC_FRONTEND_URL}",
        "--import-realm"
      ]
#    hostname: identity-access-manager-keycloak
    healthcheck:
      test: curl --fail http://localhost:8080/health/ready || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    configs:
      - target: /opt/keycloak/data/import/realm.json
        source: realm.json
    environment: #TODO: find way to have picked correctly from .env file
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: manchester19
      KC_DB_URL: "jdbc:postgresql://host.docker.internal:5432/${KC_POSTGRESQL_DATABASE}?targetServerType=primary"
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: host.docker.internal
      KC_DB_URL_PORT: 5432
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_REALM_NAME: ${KC_REALM_NAME}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_OPENHIM_CLIENT_ID: ${KC_OPENHIM_CLIENT_ID}
      KC_OPENHIM_CLIENT_SECRET: ${KC_OPENHIM_CLIENT_SECRET}
      KC_OPENHIM_ROOT_URL: ${KC_OPENHIM_ROOT_URL}
    deploy:
      placement:
        max_replicas_per_node: 1
    networks:
#      reverse-proxy:
      public:
      default:

configs:
  realm.json:
    file: ./config/realm.json
    name: realm.json-${realm_json_DIGEST:?err}
    labels:
      name: keycloak

networks:
#  reverse-proxy:
#    name: reverse-proxy_public
#    external: true
  public:
    name: keycloak_public
    external: true
  default:
